default:
  env: local
  huggingface:
    token: XXX
    base_model_id: XXX
  sagemaker:
    instance_type: XXX
    role_name: XXX
    bucket: XXX
    region: XXX
    summary_adapter: XXX
  wandb_api_key: XXX
  wandb_project: XXX
  model: XXX
  model_base_url: XXX
  model_api_key: XXX
  minio:
    host: XXX
    port: XXX
    access_key: XXX
    secret_key: XXX
  argilla:
    host: http://localhost:6900
    api_key: argilla.apikey
    workspace: admin
  OPENAI_API_KEY: XXX
product:
  argilla:
    host: XXX
    api_key: XXX
    workspace: XXX
test:
  env: test
  minio:
    host: 0.0.0.0
    port: 9000
    access_key: miniotest
    secret_key: miniotest
