default:
  env: local
  minio:
    host: XXX
    port: XXX
    access_key: XXX
    secret_key: XXX
test:
  env: test
  minio:
    host: 0.0.0.0
    port: 9000
    access_key: miniotest
    secret_key: miniotest
