name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      minio:
        image: lazybit/minio
        env:
          MINIO_ROOT_USER: miniotest
          MINIO_ROOT_PASSWORD: miniotest
        ports:
          - 9000:9000
        options: --name=minio --health-cmd "curl http://localhost:9000/minio/health/live"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run tests
        run: |
          pip install pipenv
          pipenv lock --dev
          pipenv install --dev
          pipenv run python3 -m pytest .
        env:
          ENV: test
          PYTHONPATH: ./app:.
          MINIO__HOST: 0.0.0.0
          MINIO__PORT: 9000
          MINIO__ACCESS_KEY: miniotest
          MINIO__SECRET_KEY: miniotest